openapi: 3.0.1
info:
  title: Agile Metrics Github
  description: ''
  version: 1.0.0
tags:
  - name: metrics
    description: Github Metrics
paths:
  /metrics/:
    put:
      tags:
        - metrics
      summary: Update existing metric entries pulled from github
      operationId: updateMetrics
      requestBody:
        description: Update existing metric entries pulled from github
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GithubConfigRequest'
        required: true
      responses:
        200:
          description: OK
          content:
            text/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        405:
          description: Validation exception
          content: {}
    post:
      tags:
        - metrics
      summary: Add metric entries pulled from github
      operationId: addMetrics
      requestBody:
        description:  Add metric entries pulled from github
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GithubConfigRequest'
        required: true
      responses:
        200:
          description: OK
          content:
            text/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        405:
          description: Invalid input
          content: {}


components:
  schemas:
    GithubConfigRequest:
      type: object
      properties:
        config:
          type: object
          properties:
            repositoryName:
              type: string
            teamName:
              type: string
            orgName:
              type: string
            since:
              type: string
              format: date-time

    ApiResponse:
      type: object
      properties:
        status:
          type: string