version: "3.8"

services:
  agile-metrics-github:
    image: agile-metrics-github
    security_opt:
      - seccomp:unconfined
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - GITHUB_TOKEN=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
      - CORE_METRICS_URL=http://agile-utils-service:3000
